enum AppScreen {
  splash,
  onboarding,
  assistant,
  login,
  register,
  forgot,
  home,
  search,
  results,
  vessel,
  vesselTrips,
  vesselReviews,
  purchase,
  accommodation,
  summary,
  payment,
  pix,
  boleto,
  creditCard,
  rejected,
  approved,
  ticket,
  myTrips,
  favorites,
  tracking,
  notifications,
  profile,
  settings,
  changePassword,
  accessibility,
  highContrast,
  help,
  terms,
  privacy,
  guidePurchase,
  guidePayment,
  guideAccommodation,
  ownerPanel,
}

extension AppScreenLabel on AppScreen {
  String get label {
    return switch (this) {
      AppScreen.splash => 'Splash',
      AppScreen.onboarding => 'Onboarding',
      AppScreen.assistant => 'Assistente',
      AppScreen.login => 'Login',
      AppScreen.register => 'Cadastro',
      AppScreen.forgot => 'Recuperar Senha',
      AppScreen.home => 'Início',
      AppScreen.search => 'Busca',
      AppScreen.results => 'Resultados',
      AppScreen.vessel => 'Perfil da Embarcação',
      AppScreen.vesselTrips => 'Próximas Viagens',
      AppScreen.vesselReviews => 'Avaliações',
      AppScreen.purchase => 'Compra',
      AppScreen.accommodation => 'Acomodação',
      AppScreen.summary => 'Resumo',
      AppScreen.payment => 'Pagamento',
      AppScreen.pix => 'PIX',
      AppScreen.boleto => 'Boleto',
      AppScreen.creditCard => 'Cartão',
      AppScreen.rejected => 'Pagamento Recusado',
      AppScreen.approved => 'Pagamento Aprovado',
      AppScreen.ticket => 'Bilhete Digital',
      AppScreen.myTrips => 'Minhas Viagens',
      AppScreen.favorites => 'Favoritos',
      AppScreen.tracking => 'Rastreamento',
      AppScreen.notifications => 'Notificações',
      AppScreen.profile => 'Perfil',
      AppScreen.settings => 'Configurações',
      AppScreen.changePassword => 'Alterar Senha',
      AppScreen.accessibility => 'Acessibilidade',
      AppScreen.highContrast => 'Alto Contraste',
      AppScreen.help => 'Ajuda',
      AppScreen.terms => 'Termos de Uso',
      AppScreen.privacy => 'Privacidade',
      AppScreen.guidePurchase => 'Guia de Compra',
      AppScreen.guidePayment => 'Guia de Pagamento',
      AppScreen.guideAccommodation => 'Guia de Acomodação',
      AppScreen.ownerPanel => 'Painel Proprietário',
    };
  }
}
